### ISSUE TITLE
"Rendering of the current layout would result in infinite recursion." error

### ISSUE THREAD

**Issue by chrisroos** [lazyatom/vanilla-rb#10]
I see this error fairly regularly when running the gofreerange site in development. I thought it was related to my use of Apache and Passenger but I've just been able to recreate it with a fresh Vanilla app served using `rackup`.

I don't expect you to spend any time investigating but I wanted to record what I did nonetheless.

To replicate:

```
$ git clone git@github.com:lazyatom/vanilla-rb.git
$ cd vanilla-rb
$ cd pristine_app
$ bundle
$ rackup
$ open http://localhost:9292
```
- Refresh the page in the browser 14 times.
- Refresh it for a 15th time and observe the error `[snip 'current_snip' cannot be found]`.
- Refresh if for a 16th time and observe the error `Rendering of the current layout would result in infinite recursion.`

When serving the app using `rackup`, 15 appears to be the magic number that causes the error!

I've just tried serving this same pristine Vanilla app using Apache and Passenger and see a, possibly more useful, error message on the 15th refresh:

```
[Error rendering 'link_to' - "Too many open files - getcwd"]
link_to:1:in `require'
link_to:1:in `process_text'
/private/tmp/vanilla-rb/lib/vanilla/renderers/ruby.rb:21:in `eval'
```

Again, 15 appears to be the magic number to cause the problem under Apache and Passenger.

**Comment by lazyatom** [comment]
I've seen this in the past too - thanks for pursuing it and getting some more useful information about what might be going on! I'll take a look and see if I can figure out why it might be happening.

**Comment by lazyatom** [comment]
Which version of Ruby are you using? I've just tried to replicate this and failed, but I've definitely seen it in the past so I'm sure you're not wrong!

**Comment by chrisroos** [comment]
I saw the problem under Ruby 2.2.0p0.

**Comment by lazyatom** [comment]
Hmm. I’ve just tried this again, using your exact ruby version, and haven’t managed to replicate it either. How frustrating.

I have a hunch about what might be behind it - because Soup uses the filesystem, it’s probably being very lazy about opening lots of files - but I wish I could replicate it so I could be sure. Blah.

**Comment by chrisroos** [comment]
I've just had a play at replicating the problem using the GFR site. In a fresh checkout of the site I see the "Rendering of the current layout would result in infinite recursion." error after the fifth refresh of the homepage.

    $ git clone git@github.com:freerange/site.git
    $ cd site
    $ rackup
    $ open http://localhost:9292

Assuming it is file related, do you think there are other system variables that it'd be useful to compare?

**Comment by lazyatom** [comment]
What's printed by `ulimit` when you run it in a terminal?

**Comment by chrisroos** [comment]
> What's printed by `ulimit` when you run it in a terminal?

$ ulimit
unlimited

**Comment by floehopper** [comment]
Note that this issue won't actually be fixed until lazyatom/soup#2 is incorporated into a release.

**Comment by lazyatom** [comment]
Version 1.0.14, incorporating this fix, is now on rubygems.org 👍

**Comment by floehopper** [comment]
Thanks 👍
